theme: minima
title: Aaron's test blog
author: Aaron San FIlipo
email: aaronflippo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Here's a test blog description for Aaron's test website.

# social links
twitter_username: aeornflippout # DO NOT include the @ character, or else the build will fail!
github_username:  aaronflippo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
